allow multiple key pairs

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -67,17 +67,34 @@ echo "- activate virtual env"
 #####
 echo "- setup key authentication" 1>&2
 
-if [ -e "${HOME}/.ssh/id_rsa_dominion.pub" ]; then
-    echo "key pair id_rsa_dominion already exists, skipping creation"
+sha="$(echo ${user}${host}${dest} | shasum | sed 's|\([a-f0-9]*\).*|\1|')"
+fn="id_dominion_${sha}"
+echo "${HOME}/.ssh/${fn}"
+#if [ -e "${HOME}/.ssh/id_rsa_dominion.pub" ]; then
+    #o_user="$(cat ${HOME}/.ssh/id_rsa_dominion.pub | sed 's|.*user=\([^,=]*\),\?.*|\1|')"
+    #o_host="$(cat ${HOME}/.ssh/id_rsa_dominion.pub | sed 's|.*host=\([^,=]*\),\?.*|\1|')"
+    #o_dest="$(cat ${HOME}/.ssh/id_rsa_dominion.pub | sed 's|.*dest=\([^,=]*\),\?.*|\1|')"
+    #if [[ "$user" == "$o_user" && "$host" == "$o_host" && "$dest" == "$o_dest" ]]; then
+    #    echo "key pair for this user-host-dest combination already exists, skipping key pair creation and ssh-copy-id"
+    #else
+    #    rm "${HOME}/.ssh/id_rsa_dominion"
+    #    rm "${HOME}/.ssh/id_rsa_dominion.pub"
+    #fi
+if [ -f "${HOME}/.ssh/${fn}" ]; then
+    echo "key pair for this user-host-dest combination already exists, skipping key pair creation and ssh-copy-id"
+#fi
+#if [ ! -e "${HOME}/.ssh/id_rsa_dominion.pub" ]; then
 else
-    ssh-keygen -t rsa -N "" -f "${HOME}/.ssh/id_rsa_dominion"
+    ssh-keygen -t rsa -N "" -f "${HOME}/.ssh/${fn}"
     localip=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
-    echo 'command="rsync --server -Rruve.iLsfx . '"$dest"'",from="'"$localip"'",restrict '"$(cat ${HOME}/.ssh/id_rsa_dominion.pub)" > "${HOME}/.ssh/id_rsa_dominion.pub"
+    echo "command=\"rsync --server -Rruve.iLsfx . ${dest}\",from=\"${localip}\",restrict $(cat ${HOME}/.ssh/${fn}.pub),user=${user},host=${host},dest=${dest}" > "${HOME}/.ssh/${fn}.pub"
+    ssh-copy-id -i "${HOME}/.ssh/${fn}.pub" "${user}@${host}"
 fi
-ssh-copy-id -i "${HOME}/.ssh/id_rsa_dominion.pub" "${user}@${host}"
 if [[ $? -gt 0 ]] 
 then
-    echo "ssh-copy-id failed for ${user}@${host}" 1>&2
+    echo "ssh-copy-id failed for ${user}@${host}, deleting key pair ${HOME}/.ssh/${fn}" 1>&2
+    rm "${HOME}/.ssh/${fn}"
+    rm "${HOME}/.ssh/${fn}.pub"
     exit_abnormal
 fi
 
@@ -111,6 +128,7 @@ if [ -e "${prefdir}/user.js" ]; then
     echo "user.js exists, editing entry browser.startup.homepage" 1>&2
     if (cat "${prefdir}/user.js" | grep -q "browser.startup.homepage"); then
         echo "editing entry browser.startup.homepage" 1>&2
+        #prev="$(cat ${prefdir}/user.js | sed 's|.*user=\([^,=]*\),\?.*|\1|')" #TODO: append with |
         perl -pi -e "s|user_pref\(\"browser.startup.homepage.*|user_pref\(\"browser.startup.homepage\", \"file://${overviewfile}\"\);|" "${prefdir}/user.js"
     else
         echo "user_pref(\"browser.startup.homepage\", \"file://${overviewfile}\");" >> "${prefdir}/user.js"
